### ISSUE TITLE
Error when running locally: ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by ablodge** [nert-nlp/Xposition#188]
After following instructions on the readme, I get an error when trying to import `SECRET_KEY`. 

```
Traceback (most recent call last):
  File "xposition/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\__init__.py", line 2, in <module>
    from .local import *
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\local.py", line 6, in <module>
    from .dev import *  # noqa @UnusedWildImport
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\dev.py", line 1, in <module>
    from .base import *  # noqa @UnusedWildImport
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\base.py", line 21, in <module>
    from .unversioned import SECRET_KEY
ValueError: source code string cannot contain null bytes
(Xposition) PS C:\Users\austi\Desktop\Xposition> python xposition/manage.py runserver
Traceback (most recent call last):
  File "xposition/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\austi\Anaconda3\envs\Xposition\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\__init__.py", line 2, in <module>
    from .local import *
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\local.py", line 6, in <module>
    from .dev import *  # noqa @UnusedWildImport
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\dev.py", line 1, in <module>
    from .base import *  # noqa @UnusedWildImport
  File "C:\Users\austi\Desktop\Xposition\xposition\xp\settings\base.py", line 21, in <module>
    from .unversioned import SECRET_KEY
ValueError: source code string cannot contain null bytes
```

**Comment by ablodge** [comment]
This error is due to the encoding of unversioned.py. You can change the encoding to UTF-8 in a text editor.
