### ISSUE TITLE
Can't load database locally

### ISSUE THREAD

**Issue by ablodge** [nert-nlp/Xposition#196]
When I try to migrate after adding the database file locally, I get this error:
```
python .\manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, categories, contenttypes, django_nyt, metadata, sessions, sites, thumbnail, wiki, wiki_attachments, wiki_images, wiki_notifications
Running migrations:
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying wiki.0004_merge_20190702_0004... OK
  Applying wiki.0005_auto_20190710_1913... OK
  Applying wiki.0006_auto_20190819_0056... OK
  Applying categories.0003_auto_20190819_0056... OK
  Applying categories.0004_auto_20200724_1906... OK
  Applying metadata.0016_auto_20180619_1912...Traceback (most recent call last):
  File ".\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\core\management\commands\migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\migrations\operations\models.py", line 530, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 363, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 397, in _delete_composed_index
    ", ".join(columns),
ValueError: Found wrong number (0) of constraints for metadata_usagerevision(adposition_id, obj_case, construal_id)
```

**Comment by nschneid** [comment]
Oh, hmm, I don't know how the migrations would have to change if you are using the current "real" version of the database. Have you tried regenerating them from scratch with makemigrations?

**Comment by lgessler** [comment]
@nschneid I remember when we ran into this last summer you suggested faking migrations up to the latest one used on the prod DB: `python manage.py migrate --fake $LAST_MIGRATION`

**Comment by ablodge** [comment]
Using `makemigrations` doesn't help. Can you clarify Luke's point about faking migrations? What should `$DJANGO_APP` and `$LAST_MIGRATION` stand for?

**Comment by lgessler** [comment]
@ablodge the most correct thing to do here is to (1) figure out which migrations prod has had applied to it (probably by just checking prod and seeing which migration files are present), (2) fake migrations ONLY up to that point against a copy of the production database. 

In the meantime, though, it might be worth trying running `python manage.py migrate --fake`, which will fake ALL migrations present in the repo. You should definitely make a backup of your copy of prod before you do this since this if there _are_ in fact migrations present in your repo that have not been applied to the prod db then your db will be out of sync, but I think? there haven't been any data model changes in the past year, so trying to fake all migrations is worth a go.

**Comment by ablodge** [comment]
This was caused by a faulty database file that was not up to date. The current backup of the database works fine.
